
sources:
  - name: sap
    schema: sap_adw
    description: Fontes de dados do SAP da Adventure Works.
    tables:
      - name: customer
        columns:
          - name: customerid
            tests:
              - unique
              - not_null
          - name: personid
            tests:
              - unique
      - name: salesterritory
        columns:
          - name: territoryid
            tests:
              - unique
              - not_null
      - name: address
        columns:
          - name: addressid
            tests:
              - unique
              - not_null
      - name: stateprovince
        columns:
          - name: stateprovinceid
            tests:
              - unique
              - not_null
              
                
              